apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-get-away-env
  namespace: api-get-away
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-get-away-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/api-get-away/api-get-away/env
