apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-env
  namespace: api-gateway
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: api-gateway-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/api-get-away/api-get-away/env
